apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: default
  labels:
    app.kubernetes.io/name: victoriametrics
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      protocol: TCP
  selector:
    app.kubernetes.io/name: victoriametrics
