apiVersion: v1
kind: Service
metadata:
  name: victorialogs
  namespace: default
  labels:
    app.kubernetes.io/name: victorialogs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9428
      targetPort: 9428
      protocol: TCP
  selector:
    app.kubernetes.io/name: victorialogs
